queue_rules:
  - name: default
    conditions:
      - check-success=all-ci
      - check-success=check-toml
      - check-success=audit
      - label=automerge
      - base=main
      - "#changes-requested-reviews-by=0"
      - "#approved-reviews-by>=2"
      - "approved-reviews-by=grtlr"
      - "#review-threads-unresolved=0"

pull_request_rules:
  - name: automatic merge when CI passes on main
    conditions:
      - check-success=all-ci
      - check-success=check-toml
      - check-success=audit
      - label=automerge
      - base=main
      - "#changes-requested-reviews-by=0"
      - "#approved-reviews-by>=2"
      - "approved-reviews-by=grtlr"
      - "#review-threads-unresolved=0"
    actions:
      queue:
        name: default
        method: squash

  - name: automatic approval for Dependabot pull requests
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
    actions:
      review:
        type: APPROVE
        message: Automatically approving dependabot

