queue_rules:
  - name: default
    conditions:
      - status-success=all-ci
      - status-neutral-success-toml
      - status-neutral-success=audit
      - label=automerge
      - base=main
      - "#review-threads-unresolved=0"

pull_request_rules:
  - name: automatic merge when CI passes on main
    conditions:
      - status-success=all-ci
      - status-neutral-success-toml
      - status-neutral-success=audit
      - label=automerge
      - base=main
      - "#review-threads-unresolved=0"
    actions:
      queue:
        name: default
        method: squash

  - name: automatic approval for Dependabot pull requests
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
    actions:
      review:
        type: APPROVE
        message: Automatically approving dependabot

