apiVersion: 1

deleteDatasources:
  - name: InfluxDB
    orgId: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    orgId: 1
    url: http://influx:8086
    password: root
    user: password
    database: chronicle_analytics
    basicAuth: true
    basicAuthUser:
    basicAuthPassword:
    withCredentials:
    isDefault: false
