{
 "title": "Analytics",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "aggregation_interval", "label": "Time Interval", "query": "1m,5m,15m,30m,1h,6h,12h,1d,30d" }
  ]
 },
 "panels": [
  {
   "title": "Blocks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Blocks/$aggregation_interval",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "alias": "$col Blocks",
       "groupBy": [
        { "params": [ "$aggregation_interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "iota_block_activity",
       "select": [
        [
         { "params": [ "basic_count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "Basic" ], "type": "alias" }
        ],
        [
         { "params": [ "validation_count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "Validation" ], "type": "alias" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Block States/$aggregation_interval",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$aggregation_interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "iota_block_activity",
       "select": [
        [
         { "params": [ "block_finalized_count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "Finalized" ], "type": "alias" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Block Payloads/${aggregation_interval}",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "targets": [
      {
       "alias": "$col Payloads",
       "groupBy": [
        { "params": [ "$aggregation_interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "iota_block_activity",
       "select": [
        [
         { "params": [ "transaction_count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "Transactions" ], "type": "alias" }
        ],
        [
         { "params": [ "tagged_data_count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "Tagged Data" ], "type": "alias" }
        ],
        [
         { "params": [ "candidacy_announcement_count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "Candidacy Announcement" ], "type": "alias" }
        ],
        [
         { "params": [ "no_payload_count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "Empty" ], "type": "alias" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Transaction States/$aggregation_interval",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$aggregation_interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "iota_block_activity",
       "select": [
        [
         { "params": [ "txn_pending_count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "Pending" ], "type": "alias" }
        ],
        [
         { "params": [ "txn_accepted_count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "Accepted" ], "type": "alias" }
        ],
        [
         { "params": [ "txn_confirmed_count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "Confirmed" ], "type": "alias" }
        ],
        [
         { "params": [ "txn_finalized_count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "Finalized" ], "type": "alias" }
        ],
        [
         { "params": [ "txn_failed_count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "Failed" ], "type": "alias" }
        ]
       ]
      }
     ]
    }
   ]
  },
  { "title": "Addresses and Tokens", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Ed25519 Token Distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "alias": "$col IOTA",
     "groupBy": [
      { "params": [ "$aggregation_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "iota_addresses",
     "query": "SELECT last(\"total_amount_0\"), last(\"total_amount_1\"), last(\"total_amount_2\"), last(\"total_amount_3\"), last(\"total_amount_4\"), last(\"total_amount_5\"), last(\"total_amount_6\"), last(\"total_amount_7\"), last(\"total_amount_8\"), last(\"total_amount_9\"), last(\"total_amount_10\") FROM \"iota_addresses\" WHERE $timeFilter GROUP BY time($aggregation_interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "implicit_account_total_amount_0"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "0.000001" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "implicit_account_total_amount_1"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "0.00001" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "implicit_account_total_amount_2"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "0.0001" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "implicit_account_total_amount_3"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "0.001" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "implicit_account_total_amount_4"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "0.01" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "implicit_account_total_amount_5"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "0.1" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "implicit_account_total_amount_6"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "1" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "implicit_account_total_amount_7"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "10" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "implicit_account_total_amount_8"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "100" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "implicit_account_total_amount_9"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "1000" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "implicit_account_total_amount_10"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "10000" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "implicit_account_total_amount_11"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "100000" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "implicit_account_total_amount_12"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "1M" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "implicit_account_total_amount_13"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "10M" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "implicit_account_total_amount_14"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "100M" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "implicit_account_total_amount_15"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "1B" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ed25519 Address Distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "alias": "$col IOTA",
     "groupBy": [
      { "params": [ "$aggregation_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "iota_addresses",
     "query": "SELECT last(\"total_amount_0\"), last(\"total_amount_1\"), last(\"total_amount_2\"), last(\"total_amount_3\"), last(\"total_amount_4\"), last(\"total_amount_5\"), last(\"total_amount_6\"), last(\"total_amount_7\"), last(\"total_amount_8\"), last(\"total_amount_9\"), last(\"total_amount_10\") FROM \"iota_addresses\" WHERE $timeFilter GROUP BY time($aggregation_interval) fill(null)",
     "select": [
      [
       { "params": [ "ed25519_address_count_0" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "0.000001" ], "type": "alias" }
      ],
      [
       { "params": [ "ed25519_address_count_1" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "0.00001" ], "type": "alias" }
      ],
      [
       { "params": [ "ed25519_address_count_2" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "0.0001" ], "type": "alias" }
      ],
      [
       { "params": [ "ed25519_address_count_3" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "0.001" ], "type": "alias" }
      ],
      [
       { "params": [ "ed25519_address_count_4" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "0.01" ], "type": "alias" }
      ],
      [
       { "params": [ "ed25519_address_count_5" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "0.1" ], "type": "alias" }
      ],
      [
       { "params": [ "ed25519_address_count_6" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1" ], "type": "alias" }
      ],
      [
       { "params": [ "ed25519_address_count_7" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10" ], "type": "alias" }
      ],
      [
       { "params": [ "ed25519_address_count_8" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "100" ], "type": "alias" }
      ],
      [
       { "params": [ "account_address_count_9" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1000" ], "type": "alias" }
      ],
      [
       { "params": [ "ed25519_address_count_10" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10000" ], "type": "alias" }
      ],
      [
       { "params": [ "ed25519_address_count_11" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "100000" ], "type": "alias" }
      ],
      [
       { "params": [ "ed25519_address_count_12" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1M" ], "type": "alias" }
      ],
      [
       { "params": [ "ed25519_address_count_13" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10M" ], "type": "alias" }
      ],
      [
       { "params": [ "ed25519_address_count_14" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "100M" ], "type": "alias" }
      ],
      [
       { "params": [ "ed25519_address_count_15" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1B" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Account Address Token Distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "alias": "$col IOTA",
     "groupBy": [
      { "params": [ "$aggregation_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "iota_addresses",
     "query": "SELECT last(\"total_amount_0\"), last(\"total_amount_1\"), last(\"total_amount_2\"), last(\"total_amount_3\"), last(\"total_amount_4\"), last(\"total_amount_5\"), last(\"total_amount_6\"), last(\"total_amount_7\"), last(\"total_amount_8\"), last(\"total_amount_9\"), last(\"total_amount_10\") FROM \"iota_addresses\" WHERE $timeFilter GROUP BY time($aggregation_interval) fill(null)",
     "select": [
      [
       { "params": [ "ed25519_total_amount_0" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "0.000001" ], "type": "alias" }
      ],
      [
       { "params": [ "ed25519_total_amount_1" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "0.00001" ], "type": "alias" }
      ],
      [
       { "params": [ "ed25519_total_amount_2" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "0.0001" ], "type": "alias" }
      ],
      [
       { "params": [ "ed25519_total_amount_3" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "0.001" ], "type": "alias" }
      ],
      [
       { "params": [ "ed25519_total_amount_4" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "0.01" ], "type": "alias" }
      ],
      [
       { "params": [ "ed25519_total_amount_5" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "0.1" ], "type": "alias" }
      ],
      [
       { "params": [ "ed25519_total_amount_6" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "1" ], "type": "alias" }
      ],
      [
       { "params": [ "ed25519_total_amount_7" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "10" ], "type": "alias" }
      ],
      [
       { "params": [ "ed25519_total_amount_8" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "100" ], "type": "alias" }
      ],
      [
       { "params": [ "ed25519_total_amount_9" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "1000" ], "type": "alias" }
      ],
      [
       { "params": [ "ed25519_total_amount_10" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "10000" ], "type": "alias" }
      ],
      [
       { "params": [ "ed25519_total_amount_11" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "100000" ], "type": "alias" }
      ],
      [
       { "params": [ "ed25519_total_amount_12" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "1M" ], "type": "alias" }
      ],
      [
       { "params": [ "ed25519_total_amount_13" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "10M" ], "type": "alias" }
      ],
      [
       { "params": [ "ed25519_total_amount_14" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "100M" ], "type": "alias" }
      ],
      [
       { "params": [ "ed25519_total_amount_15" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "1B" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Account Address Distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "alias": "$col IOTA",
     "groupBy": [
      { "params": [ "$aggregation_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "iota_addresses",
     "query": "SELECT last(\"total_amount_0\"), last(\"total_amount_1\"), last(\"total_amount_2\"), last(\"total_amount_3\"), last(\"total_amount_4\"), last(\"total_amount_5\"), last(\"total_amount_6\"), last(\"total_amount_7\"), last(\"total_amount_8\"), last(\"total_amount_9\"), last(\"total_amount_10\") FROM \"iota_addresses\" WHERE $timeFilter GROUP BY time($aggregation_interval) fill(null)",
     "select": [
      [
       { "params": [ "account_address_count_0" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "0.000001" ], "type": "alias" }
      ],
      [
       { "params": [ "account_address_count_1" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "0.00001" ], "type": "alias" }
      ],
      [
       { "params": [ "account_address_count_2" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "0.0001" ], "type": "alias" }
      ],
      [
       { "params": [ "account_address_count_3" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "0.001" ], "type": "alias" }
      ],
      [
       { "params": [ "account_address_count_4" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "0.01" ], "type": "alias" }
      ],
      [
       { "params": [ "account_address_count_5" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "0.1" ], "type": "alias" }
      ],
      [
       { "params": [ "account_address_count_6" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1" ], "type": "alias" }
      ],
      [
       { "params": [ "account_address_count_7" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10" ], "type": "alias" }
      ],
      [
       { "params": [ "account_address_count_8" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "100" ], "type": "alias" }
      ],
      [
       { "params": [ "account_address_count_9" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1000" ], "type": "alias" }
      ],
      [
       { "params": [ "account_address_count_10" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10000" ], "type": "alias" }
      ],
      [
       { "params": [ "account_address_count_11" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "100000" ], "type": "alias" }
      ],
      [
       { "params": [ "account_address_count_12" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1M" ], "type": "alias" }
      ],
      [
       { "params": [ "account_address_count_13" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10M" ], "type": "alias" }
      ],
      [
       { "params": [ "account_address_count_14" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "100M" ], "type": "alias" }
      ],
      [
       { "params": [ "account_address_count_15" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1B" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Implicit Account Address Token Distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "alias": "$col IOTA",
     "groupBy": [
      { "params": [ "$aggregation_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "iota_addresses",
     "query": "SELECT last(\"total_amount_0\"), last(\"total_amount_1\"), last(\"total_amount_2\"), last(\"total_amount_3\"), last(\"total_amount_4\"), last(\"total_amount_5\"), last(\"total_amount_6\"), last(\"total_amount_7\"), last(\"total_amount_8\"), last(\"total_amount_9\"), last(\"total_amount_10\") FROM \"iota_addresses\" WHERE $timeFilter GROUP BY time($aggregation_interval) fill(null)",
     "select": [
      [
       { "params": [ "account_total_amount_0" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "0.000001" ], "type": "alias" }
      ],
      [
       { "params": [ "account_total_amount_1" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "0.00001" ], "type": "alias" }
      ],
      [
       { "params": [ "account_total_amount_2" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "0.0001" ], "type": "alias" }
      ],
      [
       { "params": [ "account_total_amount_3" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "0.001" ], "type": "alias" }
      ],
      [
       { "params": [ "account_total_amount_4" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "0.01" ], "type": "alias" }
      ],
      [
       { "params": [ "account_total_amount_5" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "0.1" ], "type": "alias" }
      ],
      [
       { "params": [ "account_total_amount_6" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "1" ], "type": "alias" }
      ],
      [
       { "params": [ "account_total_amount_7" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "10" ], "type": "alias" }
      ],
      [
       { "params": [ "account_total_amount_8" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "100" ], "type": "alias" }
      ],
      [
       { "params": [ "account_total_amount_9" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "1000" ], "type": "alias" }
      ],
      [
       { "params": [ "account_total_amount_10" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "10000" ], "type": "alias" }
      ],
      [
       { "params": [ "account_total_amount_11" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "100000" ], "type": "alias" }
      ],
      [
       { "params": [ "account_total_amount_12" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "1M" ], "type": "alias" }
      ],
      [
       { "params": [ "account_total_amount_13" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "10M" ], "type": "alias" }
      ],
      [
       { "params": [ "account_total_amount_14" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "100M" ], "type": "alias" }
      ],
      [
       { "params": [ "account_total_amount_15" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "1B" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Implicit Account Address Distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "alias": "$col IOTA",
     "groupBy": [
      { "params": [ "$aggregation_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "iota_addresses",
     "query": "SELECT last(\"total_amount_0\"), last(\"total_amount_1\"), last(\"total_amount_2\"), last(\"total_amount_3\"), last(\"total_amount_4\"), last(\"total_amount_5\"), last(\"total_amount_6\"), last(\"total_amount_7\"), last(\"total_amount_8\"), last(\"total_amount_9\"), last(\"total_amount_10\") FROM \"iota_addresses\" WHERE $timeFilter GROUP BY time($aggregation_interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "implicit_account_address_count_0"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "0.000001" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "implicit_account_address_count_1"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "0.00001" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "implicit_account_address_count_2"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "0.0001" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "implicit_account_address_count_3"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "0.001" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "implicit_account_address_count_4"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "0.01" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "implicit_account_address_count_5"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "0.1" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "implicit_account_address_count_6"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "implicit_account_address_count_7"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "implicit_account_address_count_8"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "100" ], "type": "alias" }
      ],
      [
       { "params": [ "account_address_count_9" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1000" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "implicit_account_address_count_10"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10000" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "implicit_account_address_count_11"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "100000" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "implicit_account_address_count_12"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1M" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "implicit_account_address_count_13"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10M" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "implicit_account_address_count_14"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "100M" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "implicit_account_address_count_15"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1B" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "NFT Address Token Distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "alias": "$col IOTA",
     "groupBy": [
      { "params": [ "$aggregation_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "iota_addresses",
     "query": "SELECT last(\"total_amount_0\"), last(\"total_amount_1\"), last(\"total_amount_2\"), last(\"total_amount_3\"), last(\"total_amount_4\"), last(\"total_amount_5\"), last(\"total_amount_6\"), last(\"total_amount_7\"), last(\"total_amount_8\"), last(\"total_amount_9\"), last(\"total_amount_10\") FROM \"iota_addresses\" WHERE $timeFilter GROUP BY time($aggregation_interval) fill(null)",
     "select": [
      [
       { "params": [ "nft_total_amount_0" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "0.000001" ], "type": "alias" }
      ],
      [
       { "params": [ "nft_total_amount_1" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "0.00001" ], "type": "alias" }
      ],
      [
       { "params": [ "nft_total_amount_2" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "0.0001" ], "type": "alias" }
      ],
      [
       { "params": [ "nft_total_amount_3" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "0.001" ], "type": "alias" }
      ],
      [
       { "params": [ "nft_total_amount_4" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "0.01" ], "type": "alias" }
      ],
      [
       { "params": [ "nft_total_amount_5" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "0.1" ], "type": "alias" }
      ],
      [
       { "params": [ "nft_total_amount_6" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "1" ], "type": "alias" }
      ],
      [
       { "params": [ "nft_total_amount_7" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "10" ], "type": "alias" }
      ],
      [
       { "params": [ "nft_total_amount_8" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "100" ], "type": "alias" }
      ],
      [
       { "params": [ "nft_total_amount_9" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "1000" ], "type": "alias" }
      ],
      [
       { "params": [ "nft_total_amount_10" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "10000" ], "type": "alias" }
      ],
      [
       { "params": [ "nft_total_amount_11" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "100000" ], "type": "alias" }
      ],
      [
       { "params": [ "nft_total_amount_12" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "1M" ], "type": "alias" }
      ],
      [
       { "params": [ "nft_total_amount_13" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "10M" ], "type": "alias" }
      ],
      [
       { "params": [ "nft_total_amount_14" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "100M" ], "type": "alias" }
      ],
      [
       { "params": [ "nft_total_amount_15" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "1B" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "NFT Address Distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "alias": "$col IOTA",
     "groupBy": [
      { "params": [ "$aggregation_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "iota_addresses",
     "query": "SELECT last(\"total_amount_0\"), last(\"total_amount_1\"), last(\"total_amount_2\"), last(\"total_amount_3\"), last(\"total_amount_4\"), last(\"total_amount_5\"), last(\"total_amount_6\"), last(\"total_amount_7\"), last(\"total_amount_8\"), last(\"total_amount_9\"), last(\"total_amount_10\") FROM \"iota_addresses\" WHERE $timeFilter GROUP BY time($aggregation_interval) fill(null)",
     "select": [
      [
       { "params": [ "nft_address_count_0" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "0.000001" ], "type": "alias" }
      ],
      [
       { "params": [ "nft_address_count_1" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "0.00001" ], "type": "alias" }
      ],
      [
       { "params": [ "nft_address_count_2" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "0.0001" ], "type": "alias" }
      ],
      [
       { "params": [ "nft_address_count_3" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "0.001" ], "type": "alias" }
      ],
      [
       { "params": [ "nft_address_count_4" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "0.01" ], "type": "alias" }
      ],
      [
       { "params": [ "nft_address_count_5" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "0.1" ], "type": "alias" }
      ],
      [
       { "params": [ "nft_address_count_6" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1" ], "type": "alias" }
      ],
      [
       { "params": [ "nft_address_count_7" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10" ], "type": "alias" }
      ],
      [
       { "params": [ "nft_address_count_8" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "100" ], "type": "alias" }
      ],
      [
       { "params": [ "account_address_count_9" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1000" ], "type": "alias" }
      ],
      [
       { "params": [ "nft_address_count_10" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10000" ], "type": "alias" }
      ],
      [
       { "params": [ "nft_address_count_11" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "100000" ], "type": "alias" }
      ],
      [
       { "params": [ "nft_address_count_12" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1M" ], "type": "alias" }
      ],
      [
       { "params": [ "nft_address_count_13" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10M" ], "type": "alias" }
      ],
      [
       { "params": [ "nft_address_count_14" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "100M" ], "type": "alias" }
      ],
      [
       { "params": [ "nft_address_count_15" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1B" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Anchor Address Token Distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "alias": "$col IOTA",
     "groupBy": [
      { "params": [ "$aggregation_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "iota_addresses",
     "query": "SELECT last(\"total_amount_0\"), last(\"total_amount_1\"), last(\"total_amount_2\"), last(\"total_amount_3\"), last(\"total_amount_4\"), last(\"total_amount_5\"), last(\"total_amount_6\"), last(\"total_amount_7\"), last(\"total_amount_8\"), last(\"total_amount_9\"), last(\"total_amount_10\") FROM \"iota_addresses\" WHERE $timeFilter GROUP BY time($aggregation_interval) fill(null)",
     "select": [
      [
       { "params": [ "anchor_total_amount_0" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "0.000001" ], "type": "alias" }
      ],
      [
       { "params": [ "anchor_total_amount_1" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "0.00001" ], "type": "alias" }
      ],
      [
       { "params": [ "anchor_total_amount_2" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "0.0001" ], "type": "alias" }
      ],
      [
       { "params": [ "anchor_total_amount_3" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "0.001" ], "type": "alias" }
      ],
      [
       { "params": [ "anchor_total_amount_4" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "0.01" ], "type": "alias" }
      ],
      [
       { "params": [ "anchor_total_amount_5" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "0.1" ], "type": "alias" }
      ],
      [
       { "params": [ "anchor_total_amount_6" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "1" ], "type": "alias" }
      ],
      [
       { "params": [ "anchor_total_amount_7" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "10" ], "type": "alias" }
      ],
      [
       { "params": [ "anchor_total_amount_8" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "100" ], "type": "alias" }
      ],
      [
       { "params": [ "anchor_total_amount_9" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "1000" ], "type": "alias" }
      ],
      [
       { "params": [ "anchor_total_amount_10" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "10000" ], "type": "alias" }
      ],
      [
       { "params": [ "anchor_total_amount_11" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "100000" ], "type": "alias" }
      ],
      [
       { "params": [ "anchor_total_amount_12" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "1M" ], "type": "alias" }
      ],
      [
       { "params": [ "anchor_total_amount_13" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "10M" ], "type": "alias" }
      ],
      [
       { "params": [ "anchor_total_amount_14" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "100M" ], "type": "alias" }
      ],
      [
       { "params": [ "anchor_total_amount_15" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "1B" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Anchor Address Distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "alias": "$col IOTA",
     "groupBy": [
      { "params": [ "$aggregation_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "iota_addresses",
     "query": "SELECT last(\"total_amount_0\"), last(\"total_amount_1\"), last(\"total_amount_2\"), last(\"total_amount_3\"), last(\"total_amount_4\"), last(\"total_amount_5\"), last(\"total_amount_6\"), last(\"total_amount_7\"), last(\"total_amount_8\"), last(\"total_amount_9\"), last(\"total_amount_10\") FROM \"iota_addresses\" WHERE $timeFilter GROUP BY time($aggregation_interval) fill(null)",
     "select": [
      [
       { "params": [ "anchor_address_count_0" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "0.000001" ], "type": "alias" }
      ],
      [
       { "params": [ "anchor_address_count_1" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "0.00001" ], "type": "alias" }
      ],
      [
       { "params": [ "anchor_address_count_2" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "0.0001" ], "type": "alias" }
      ],
      [
       { "params": [ "anchor_address_count_3" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "0.001" ], "type": "alias" }
      ],
      [
       { "params": [ "anchor_address_count_4" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "0.01" ], "type": "alias" }
      ],
      [
       { "params": [ "anchor_address_count_5" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "0.1" ], "type": "alias" }
      ],
      [
       { "params": [ "anchor_address_count_6" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1" ], "type": "alias" }
      ],
      [
       { "params": [ "anchor_address_count_7" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10" ], "type": "alias" }
      ],
      [
       { "params": [ "anchor_address_count_8" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "100" ], "type": "alias" }
      ],
      [
       { "params": [ "account_address_count_9" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1000" ], "type": "alias" }
      ],
      [
       { "params": [ "anchor_address_count_10" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10000" ], "type": "alias" }
      ],
      [
       { "params": [ "anchor_address_count_11" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "100000" ], "type": "alias" }
      ],
      [
       { "params": [ "anchor_address_count_12" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1M" ], "type": "alias" }
      ],
      [
       { "params": [ "anchor_address_count_13" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10M" ], "type": "alias" }
      ],
      [
       { "params": [ "anchor_address_count_14" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "100M" ], "type": "alias" }
      ],
      [
       { "params": [ "anchor_address_count_15" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1B" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "IOTA Tokens Booked/$aggregation_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "alias": "Number of Booked IOTA Tokens",
     "groupBy": [
      { "params": [ "$aggregation_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "iota_base_token_activity",
     "select": [
      [
       { "params": [ "booked_amount" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "IOTA Tokens Transferred/$aggregation_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "alias": "Number of Transferred IOTA Tokens",
     "groupBy": [
      { "params": [ "$aggregation_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "iota_base_token_activity",
     "select": [
      [
       { "params": [ "transferred_amount" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Addresses with Balance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "alias": "Number of $col addresses",
     "groupBy": [
      { "params": [ "$aggregation_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "iota_addresses",
     "select": [
      [
       {
        "params": [
         "ed25519_address_with_balance_count"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Ed25519" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "account_address_with_balance_count"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Account" ], "type": "alias" }
      ],
      [
       { "params": [ "nft_address_with_balance_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "NFT" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "anchor_address_with_balance_count"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Anchor" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "implicit_account_address_with_balance_count"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Implicit Account" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Number of Daily Active Addresses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "alias": "Addresses",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "iota_daily_active_addresses",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Outputs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Number of Outputs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$col Outputs",
     "groupBy": [
      { "params": [ "$aggregation_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "iota_ledger_outputs",
     "select": [
      [
       { "params": [ "basic_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Basic" ], "type": "alias" }
      ],
      [
       { "params": [ "account_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Account" ], "type": "alias" }
      ],
      [
       { "params": [ "nft_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "NFT" ], "type": "alias" }
      ],
      [
       { "params": [ "foundry_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Foundry" ], "type": "alias" }
      ],
      [
       { "params": [ "delegation_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Delegation" ], "type": "alias" }
      ],
      [
       { "params": [ "anchor_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Anchor" ], "type": "alias" }
      ],
      [
       { "params": [ "block_issuer_accounts" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Block Issuer Account" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Tokens Held by Outputs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "IOTA" } },
   "targets": [
    {
     "alias": "$col Outputs",
     "groupBy": [
      { "params": [ "$aggregation_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "iota_ledger_outputs",
     "select": [
      [
       { "params": [ "basic_amount" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Basic" ], "type": "alias" }
      ],
      [
       { "params": [ "account_amount" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Account" ], "type": "alias" }
      ],
      [
       { "params": [ "foundry_amount" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Foundry" ], "type": "alias" }
      ],
      [
       { "params": [ "nft_amount" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "NFT" ], "type": "alias" }
      ],
      [
       { "params": [ "delegation_amount" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Delegation" ], "type": "alias" }
      ],
      [
       { "params": [ "delegated_amount" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Delegated Amount in" ], "type": "alias" }
      ],
      [
       { "params": [ "anchor_amount" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Anchor" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  { "title": "Output Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Account Activity Counts/$aggregation_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$aggregation_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "iota_output_activity",
     "select": [
      [
       { "params": [ "account_created_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Created" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "account_block_issuer_key_rotated_count"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Block Issuer Key Rotated" ], "type": "alias" }
      ],
      [
       { "params": [ "account_destroyed_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Destroyed" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Anchor Activity Counts/$aggregation_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$aggregation_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "iota_output_activity",
     "select": [
      [
       { "params": [ "anchor_created_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Created" ], "type": "alias" }
      ],
      [
       { "params": [ "anchor_governor_changed_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Governor Changed" ], "type": "alias" }
      ],
      [
       { "params": [ "anchor_state_changed_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "State Changed" ], "type": "alias" }
      ],
      [
       { "params": [ "anchor_destroyed_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Destroyed" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Foundry Activity Counts/$aggregation_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$aggregation_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "iota_output_activity",
     "select": [
      [
       { "params": [ "foundry_created_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Created" ], "type": "alias" }
      ],
      [
       { "params": [ "foundry_transferred_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Transferred" ], "type": "alias" }
      ],
      [
       { "params": [ "foundry_destroyed_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Destroyed" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "NFT Activity Counts/$aggregation_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$aggregation_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "iota_output_activity",
     "select": [
      [
       { "params": [ "nft_created_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Created" ], "type": "alias" }
      ],
      [
       { "params": [ "nft_transferred_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Transferred" ], "type": "alias" }
      ],
      [
       { "params": [ "nft_destroyed_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Destroyed" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Delegation Activity Counts/$aggregation_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$aggregation_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "iota_output_activity",
     "select": [
      [
       { "params": [ "delegation_created_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Created" ], "type": "alias" }
      ],
      [
       { "params": [ "delegation_delayed_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Delayed" ], "type": "alias" }
      ],
      [
       { "params": [ "delegation_destroyed_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Destroyed" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Native Token Activity Counts/$aggregation_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$aggregation_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "iota_output_activity",
     "select": [
      [
       { "params": [ "native_token_minted_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Minted" ], "type": "alias" }
      ],
      [
       { "params": [ "native_token_melted_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Melted" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Transaction Distribution by Created Outputs /${aggregation_interval}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$aggregation_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "iota_transaction_size_distribution",
     "query": "SELECT last(\"output_1\"), last(\"output_2\"), last(\"output_3\"), last(\"output_4\"), last(\"output_5\"), last(\"output_6\"), last(\"output_7\"), last(\"output_small\"), last(\"output_medium\"), last(\"output_large\"), last(\"output_huge\") FROM \"iota_transaction_size_distribution\" WHERE $timeFilter GROUP BY time($aggregation_interval) fill(null)",
     "select": [
      [
       { "params": [ "output_1" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1" ], "type": "alias" }
      ],
      [
       { "params": [ "output_2" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "2" ], "type": "alias" }
      ],
      [
       { "params": [ "output_3" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "3" ], "type": "alias" }
      ],
      [
       { "params": [ "output_4" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "4" ], "type": "alias" }
      ],
      [
       { "params": [ "output_5" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "5" ], "type": "alias" }
      ],
      [
       { "params": [ "output_6" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "6" ], "type": "alias" }
      ],
      [
       { "params": [ "output_7" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "7" ], "type": "alias" }
      ],
      [
       { "params": [ "output_small" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "[8..16)" ], "type": "alias" }
      ],
      [
       { "params": [ "output_medium" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "[16..32)" ], "type": "alias" }
      ],
      [
       { "params": [ "output_large" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "[32..64)" ], "type": "alias" }
      ],
      [
       { "params": [ "output_huge" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "[64..128)" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Transaction Distribution by Consumed Outputs /${aggregation_interval}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$aggregation_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "iota_transaction_size_distribution",
     "query": "SELECT last(\"input_0\"), last(\"input_1\"), last(\"input_2\"), last(\"input_3\"), last(\"input_4\"), last(\"input_5\"), last(\"input_6\"), last(\"input_7\"), last(\"input_small\"), last(\"input_medium\"), last(\"input_large\"), last(\"input_huge\") FROM \"iota_transaction_size_distribution\" WHERE $timeFilter GROUP BY time($aggregation_interval) fill(null)",
     "select": [
      [
       { "params": [ "input_1" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1" ], "type": "alias" }
      ],
      [
       { "params": [ "input_2" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "2" ], "type": "alias" }
      ],
      [
       { "params": [ "input_3" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "3" ], "type": "alias" }
      ],
      [
       { "params": [ "input_4" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "4" ], "type": "alias" }
      ],
      [
       { "params": [ "input_5" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "5" ], "type": "alias" }
      ],
      [
       { "params": [ "input_6" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "6" ], "type": "alias" }
      ],
      [
       { "params": [ "input_7" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "7" ], "type": "alias" }
      ],
      [
       { "params": [ "input_small" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "[8..16)" ], "type": "alias" }
      ],
      [
       { "params": [ "input_medium" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "[16..32)" ], "type": "alias" }
      ],
      [
       { "params": [ "input_large" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "[32..64)" ], "type": "alias" }
      ],
      [
       { "params": [ "input_huge" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "[64..128)" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Unlock Conditions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Unlock Conditions by Type",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "$col Unlock Conditions",
       "groupBy": [
        { "params": [ "$aggregation_interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "iota_unlock_conditions",
       "select": [
        [
         { "params": [ "timelock_count" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Timelock" ], "type": "alias" }
        ],
        [
         { "params": [ "storage_deposit_return_count" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Storage Deposit Return" ], "type": "alias" }
        ],
        [
         { "params": [ "expiration_count" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Expiration" ], "type": "alias" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Tokens Held by Outputs with Unlock Conditions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "IOTA" } },
     "targets": [
      {
       "alias": "$col Unlock Conditions",
       "groupBy": [
        { "params": [ "$aggregation_interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "iota_unlock_conditions",
       "select": [
        [
         { "params": [ "timelock_amount" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ " / 1000000" ], "type": "math" },
         { "params": [ "Timelock" ], "type": "alias" }
        ],
        [
         { "params": [ "storage_deposit_return_amount" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ " / 1000000" ], "type": "math" },
         { "params": [ "Storage Deposit Return" ], "type": "alias" }
        ],
        [
         { "params": [ "expiration_amount" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ " / 1000000" ], "type": "math" },
         { "params": [ "Expiration" ], "type": "alias" }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Features",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Features",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "targets": [
      {
       "alias": "$col Count",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "iota_features",
       "select": [
        [
         { "params": [ "block_issuer_count" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Block Issuer" ], "type": "alias" }
        ],
        [
         { "params": [ "native_tokens_count" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Native Tokens" ], "type": "alias" }
        ],
        [
         { "params": [ "staking_count" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Staking" ], "type": "alias" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Tokens Held by Outputs with Features",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "IOTA" } },
     "targets": [
      {
       "alias": "$col Amount",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "iota_features",
       "select": [
        [
         { "params": [ "block_issuer_amount" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Block Issuer" ], "type": "alias" }
        ],
        [
         { "params": [ "native_tokens_amount" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Native Tokens" ], "type": "alias" }
        ],
        [
         { "params": [ "staked_amount" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Staked" ], "type": "alias" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Active Block Issuers/$aggregation_interval",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "targets": [
      {
       "alias": "Active Block Issuers",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "iota_block_issuer_activity",
       "select": [
        [
         { "params": [ "active_issuer_count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Mana",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 102 },
   "collapsed": true,
   "panels": [
    {
     "title": "Mana Activity/$aggregation_interval",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "iota_mana_activity",
       "select": [
        [
         { "params": [ "mana_burned" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "Mana Burned" ], "type": "alias" }
        ],
        [
         { "params": [ "bic_burned" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "Block Issuer Credits Burned" ], "type": "alias" }
        ],
        [
         { "params": [ "rewards_claimed" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "Rewards Claimed" ], "type": "alias" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Reference Mana Cost",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "iota_slot_commitment",
       "select": [
        [
         { "params": [ "reference_mana_cost" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Reference Mana Cost" ], "type": "alias" }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Byte Cost",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 103 },
   "collapsed": true,
   "panels": [
    {
     "title": "Amount in Storage Deposit Return Unlock Condition",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "IOTA" } },
     "targets": [
      {
       "alias": "Return Amount",
       "groupBy": [
        { "params": [ "$aggregation_interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "iota_unlock_conditions",
       "select": [
        [
         {
          "params": [
           "storage_deposit_return_inner_amount"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ " / 1000000" ], "type": "math" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Storage Deposit",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "IOTA" } },
     "targets": [
      {
       "alias": "Storage Deposit",
       "groupBy": [
        { "params": [ "$aggregation_interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "iota_ledger_size",
       "select": [
        [
         { "params": [ "total_storage_score" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ " / 1000000" ], "type": "math" }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}