{
 "title": "Chronicle",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Last Milestone Index",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sync_metrics",
     "select": [
      [
       { "params": [ "milestone_index" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Milestone Sync Time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "Network: \"$tag_network_name\", Chronicle Version: $tag_chronicle_version",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "chronicle_version" ], "type": "tag" },
      { "params": [ "network_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sync_metrics",
     "select": [
      [
       { "params": [ "sync_time" ], "type": "field" },
       { "params": [ "95" ], "type": "percentile" }
      ]
     ]
    }
   ]
  },
  {
   "title": "MongoDB Database Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "mongodb_dbstats_totalSize{database=\"chronicle\"}",
     "legendFormat": "{{ database }}"
    }
   ]
  },
  {
   "title": "MongoDB Index Info",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "mongodb_collstats_storageStats_indexSizes_ledger_update_index",
     "legendFormat": "{{ collection }}"
    },
    {
     "expr": "mongodb_collstats_storageStats_indexSizes_output_spent_index",
     "legendFormat": "{{ collection }}"
    },
    {
     "expr": "mongodb_collstats_storageStats_indexSizes_block_referenced_index",
     "legendFormat": "{{ collection }}"
    },
    {
     "expr": "mongodb_dbstats_indexSize{database=\"chronicle\"}",
     "legendFormat": "{{ database }}"
    }
   ]
  },
  {
   "title": "Chronicle Mongo Database Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "mongodb_collstats_storageStats_size{database=\"chronicle\"}",
     "legendFormat": "{{ collection }}"
    }
   ]
  }
 ]
}