openapi: 3.0.3
info:
  title: Explorer REST API
  description: This document specifies the REST API for Chronicle software.
  contact:
    email: contact@iota.org
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
  version: 1.0.0
externalDocs:
  description: Find out more about IOTA
  url: "https://iota.org"
servers:
  - url: "http://127.0.0.1:8000"
tags:
  - name: ledger
    description: Everything about the ledger.
  - name: balance
    description: Everything about balances.
paths:
  /api/explorer/v2/balance/{address}:
    get:
      tags:
        - balance
      summary: Returns an address's balance.
      description: >-
        Returns the balance of IOTA tokens owned by a given bech32 address.
      parameters:
        - $ref: "#/components/parameters/address"
      responses:
        "200":
          description: Successful operation.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BalanceResponse"
              examples:
                default:
                  $ref: "#/components/examples/balance-example"
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          $ref: "#/components/responses/NoResults"
        "500":
          $ref: "#/components/responses/InternalError"
  /api/explorer/v2/ledger/updates/by-address/{address}:
    get:
      tags:
        - ledger
      summary: Get all ledger updates involving a given bech32 address.
      description: >-
        Get all ledger updates involving a given bech32 address.
      parameters:
        - $ref: "#/components/parameters/address"
        - $ref: "#/components/parameters/pageSize"
        - $ref: "#/components/parameters/sort"
        - $ref: "#/components/parameters/startMilestoneIndex"
        - $ref: "#/components/parameters/cursor"
      responses:
        "200":
          description: Successful operation.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LedgerUpdatesByAddressResponse"
              examples:
                default:
                  $ref: "#/components/examples/ledger-updates-address-example"
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          $ref: "#/components/responses/NoResults"
        "500":
          $ref: "#/components/responses/InternalError"
  /api/explorer/v2/ledger/updates/by-milestone/{milestoneId}:
    get:
      tags:
        - ledger
      summary: Get all ledger updates for a given milestone index.
      description: Get all ledger updates for a given milestone index.
      parameters:
        - $ref: "#/components/parameters/milestoneId"
        - $ref: "#/components/parameters/pageSize"
        - $ref: "#/components/parameters/cursor"
      responses:
        "200":
          description: Successful operation.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LedgerUpdatesByMilestoneResponse"
              examples:
                default:
                  $ref: "#/components/examples/ledger-updates-milestone-example"
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          $ref: "#/components/responses/NoResults"
        "500":
          $ref: "#/components/responses/InternalError"
components:
  schemas:
    BalanceResponse:
      description: The balance of IOTA tokens owned by an address.
      properties:
        totalBalance:
          type: string
          description: >-
            The total value held in unspent outputs owned by the given address 
            (includes funds held in storage deposit).
        sigLockedBalance:
          type: string
          description: >-
            The sum of value held in unspent outputs owned by the given address 
            that are signature locked ("trivially unlockable").
        ledgerIndex:
          type: integer
          description: The ledger index for which the balance calculation was performed.
    LedgerUpdatesByMilestoneResponse:
      description: A list of ledger updates associated with a milestone.
      properties:
        milestoneIndex:
          type: integer
          description: The index of the milestone.
        items:
          type: array
          description: A list of ledger updates.
          items:
            properties:
              address:
                type: string
                description: bech32 address that is referenced by the outputs.
              outputId:
                type: string
                description: >-
                  The output ID (transaction hash + output index) of the update. 
                  Hex-encoded with 0x prefix.
              isSpent:
                type: boolean
                description: Indicates if the output is spent or not.
            required:
              - address
              - outputId
              - isSpent
        cursor:
          type: string
          description: The cursor which can be used to retrieve the next logical page of results.
      required:
        - milestoneIndex
        - items
    LedgerUpdatesByAddressResponse:
      description: A list of ledger updates associated with an address.
      properties:
        address:
          type: string
          description: bech32 address that is referenced by the outputs.
        items:
          type: array
          description: A list of ledger updates.
          items:
            properties:
              milestoneIndex:
                type: integer
                description: The index of the milestone.
              milestoneTimestamp:
                type: integer
                description: The timestamp at which the milestone was issued.
              outputId:
                type: string
                description: >-
                  The output ID (transaction hash + output index) of the update. 
                  Hex-encoded with 0x prefix.
              isSpent:
                type: boolean
                description: Indicates if the output is spent or not.
            required:
              - milestoneIndex
              - milestoneTimestamp
              - outputId
              - isSpent
        cursor:
          type: string
          description: The cursor which can be used to retrieve the next logical page of results.
      required:
        - address
        - items
  responses:
    NoResults:
      description: >-
        Unsuccessful operation: indicates that the requested data was not found.
      content:
        application/json:
          schema:
            $ref: "https://raw.githubusercontent.com/iotaledger/tips/stardust-api/tips/TIP-0025/core-rest-api.yaml#/components/schemas/NotFoundResponse"
    BadRequest:
      description: "Unsuccessful operation: indicates that the provided parameters are invalid."
      content:
        application/json:
          schema:
            $ref: "https://raw.githubusercontent.com/iotaledger/tips/stardust-api/tips/TIP-0025/core-rest-api.yaml#/components/schemas/BadRequestResponse"
    InternalError:
      description: >-
        Unsuccessful operation: indicates that an unexpected, internal
        server error happened which prevented the node from fulfilling the
        request.
      content:
        application/json:
          schema:
            $ref: "https://raw.githubusercontent.com/iotaledger/tips/stardust-api/tips/TIP-0025/core-rest-api.yaml#/components/schemas/InternalErrorResponse"
  parameters:
    address:
      in: path
      name: address
      schema:
        type: string
      example: iota1qpf0mlq8yxpx2nck8a0slxnzr4ef2ek8f5gqxlzd0wasgp73utryj430ldu
      required: true
      description: bech32 address that is referenced by the outputs.
    milestoneId:
      in: path
      name: milestoneId
      schema:
        type: string
      example: "0x7a09324557e9200f39bf493fc8fd6ac43e9ca750c6f6d884cc72386ddcb7d695"
      required: true
      description: Milestone id for which to receive ledger updates.
    pageSize:
      in: query
      name: pageSize
      schema:
        type: number
      example: 100
      description: Requested page size. Overridden by the cursor if provided.
    sort:
      in: query
      name: sort
      schema:
        type: string
      example: newest
      description: >-
        Describes the sort order, either by oldest or newest. This value is NOT
        overridden by the cursor, and thus can be used to back-page.
    startMilestoneIndex:
      in: query
      name: startMilestoneIndex
      schema:
        type: number
      example: 500000
      description: >-
        The milestone index at which to start retrieving results. This will be overridden 
        by the cursor if provided.
    cursor:
      in: query
      name: cursor
      schema:
        type: string
      example: 1643383242.fa0de75d225cca2799395e5fc340702fc7eac821d2bdd79911126f131ae097a20100.100
      description: The cursor which can be used to retrieve the next logical page of results.
  examples:
    balance-example:
      value:
        totalBalance: 100000
        sigLockedBalance: 99900
        ledgerIndex: 500000
    ledger-updates-address-example:
      value:
        address: iota1qpf0mlq8yxpx2nck8a0slxnzr4ef2ek8f5gqxlzd0wasgp73utryj430ldu
        items:
          - milestoneIndex: 500000
            milestoneTimestamp: 1660065130
            outputId: fa0de75d225cca2799395e5fc340702fc7eac821d2bdd79911126f131ae097a20100
            isSpent: false
          - milestoneIndex: 500000
            milestoneTimestamp: 1660065129
            outputId: fa0de75d225cca2799395e5fc340702fc7eac821d2bdd79911126f131ae097a20000
            isSpent: true
        cursor: 1643383242.fa0de75d225cca2799395e5fc340702fc7eac821d2bdd79911126f131ae097a20100.true.100
    ledger-updates-milestone-example:
      value:
        milestoneIndex: 500000
        items:
          - address: iota1qpf0mlq8yxpx2nck8a0slxnzr4ef2ek8f5gqxlzd0wasgp73utryj430ldu
            outputId: fa0de75d225cca2799395e5fc340702fc7eac821d2bdd79911126f131ae097a20100
            isSpent: false
          - address: iota1qpf0mlq8yxpx2nck8a0slxnzr4ef2ek8f5gqxlzd0wasgp73utryj430ldb
            outputId: fa0de75d225cca2799395e5fc340702fc7eac821d2bdd79911126f131ae097a20000
            isSpent: true
        cursor: fa0de75d225cca2799395e5fc340702fc7eac821d2bdd79911126f131ae097a20100.true.100
