name: Check and Test

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      rust:
        required: true
        type: string

jobs:
  check-and-test:
    name: '${{ inputs.os }}, ${{ inputs.rust }}'
    runs-on: ${{ inputs.os }}
    # Unfortunately, we can't do this right now because `indexmap` does not seem to follow semver.
    # env:
    #   RUSTFLAGS: -D warnings -D missing-docs
    steps:
      - uses: actions/checkout@v2

      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Rust (${{ inputs.rust }})
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ inputs.rust }}
          override: true

      - uses: Swatinem/rust-cache@v1

      - name: Check (all features)
        uses: actions-rs/cargo@v1
        with:
          command: ci-check-all

      - name: Check (INX only)
        if: contains(inputs.os, 'ubuntu')
        uses: actions-rs/cargo@v1
        with:
          command: ci-check-inx

      - name: Check (API only)
        if: contains(inputs.os, 'ubuntu')
        uses: actions-rs/cargo@v1
        with:
          command: ci-check-api

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: ci-test

      - name: Doc Test
        uses: actions-rs/cargo@v1
        with:
          command: ci-doctest
