name: Build Docker Image

on:
  workflow_call:
    inputs: {}

jobs:
  build:
    name: docker-compose build 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Docker image
        run: docker-compose -f ./docker/docker-compose.hornet.yml build
