name: Check Formatting

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      rust:
        required: true
        type: string

jobs:
  format:
    name: "${{inputs.os}}, ${{inputs.rust}}"
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ inputs.rust }}
          override: true
          components: rustfmt

      - uses: actions-rs/cargo@v1
        with:
          command: ci-fmt
