name: Integration Tests

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      rust:
        required: true
        type: string
      mongodb:
        required: true
        type: string

jobs:
  test-int:
    name: "${{ inputs.os }}, ${{ inputs.rust }}"
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Rust (${{ inputs.rust }})
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ inputs.rust }}
          override: true

      - uses: Swatinem/rust-cache@v1

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: ${{ inputs.mongodb }}
          mongodb-replica-set: test-rs

      - name: Test DB
        uses: actions-rs/cargo@v1
        with:
          command: ci-test-int
