name: Canary

on:
  schedule:
    - cron: '4 20 * * SUN'

jobs:

  udeps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: --force cargo-udeps

      - uses: actions-rs/cargo@v1
        with:
          command: ci-udeps
