name: canary

on:
  schedule:
    - cron: '4 20 * * SUN'

jobs:

  check-and-test-1:
    name: "check and test"
    uses: ./.github/workflows/_check.yml
    with: { os: windows-latest, rust: stable }

  check-and-test-2:
    name: "check and test"
    uses: ./.github/workflows/_check.yml
    with: { os: macos-latest, rust: stable }

  check-and-test-3:
    name: "check and test"
    uses: ./.github/workflows/_check.yml
    with: { os: ubuntu-latest, rust: beta }
  
  check-and-test-4:
    name: "check and test"
    uses: ./.github/workflows/_check.yml
    with: { os: windows-latest, rust: beta }

  check-and-test-5:
    name: "check and test"
    uses: ./.github/workflows/_check.yml
    with: { os: macos-latest, rust: beta }

  docker:
    uses: ./.github/workflows/_docker.yml

  clippy:
    uses: ./.github/workflows/_clippy.yml
    with: { os: ubuntu-latest, rust: beta }

  udeps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: --force cargo-udeps

      - uses: actions-rs/cargo@v1
        with:
          command: ci-udeps

  check-all-features:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: --force cargo-all-features

      - uses: actions-rs/cargo@v1
        with:
          command: check-all-features
    
