name: Check Cargo.toml

on:
  push:
    paths:
      - "**/Cargo.toml"
  pull_request:
    paths:
      - "**/Cargo.toml"

jobs:
  check-toml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: --force cargo-sort

      - uses: actions-rs/cargo@v1
        with:
          command: ci-toml
