name: Coverage

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/coverage.yml"
      - ".github/workflows/scripts/coverage.sh"
      - "**.rs"
      - "**.toml"
  pull_request:
    paths:
      - ".github/workflows/coverage.yml"
      - ".github/workflows/scripts/coverage.sh"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: llvm-tools-preview

      - uses: actions-rs/install@v0.1
        with:
          crate: cargo-binutils
          version: 0.3.3

      - uses: actions-rs/install@v0.1
        with:
          crate: rustfilt
          version: 0.2.1

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: "6.0"
          mongodb-username: root
          mongodb-password: root
          # FIXME: Currently we cannot configure this action to use authentication together with replica sets as mentioned here: 
          # https://github.com/supercharge/mongodb-github-action#with-authentication-mongodb---auth-flag
          # Apparently, the solution is to write a script that sets up the user beforehand.
          #mongodb-replica-set: test-rs

      - name: Run test coverage
        run: bash .github/workflows/scripts/coverage.sh
        env:
          MONGODB_CONN_STR: mongodb://root:root@localhost:27017

      - uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage/coverage.info
