name: Chronicle Project

on:
  issues:
    types: 
      - opened

jobs:
  add-to-project:
    name: Add issue to Chronicle project
    runs-on: ubuntu-latest
    steps:
      - name: Add To GitHub projects
        uses: actions/add-to-project@v0.3.0
        with:
          project-url: https://github.com/orgs/iotaledger/projects/13
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
