name: Test IOTA Documentation Build

on:
  push:
    branches:
      - main
    paths:
      - "documentation/**"
  pull_request:
    paths:
      - "documentation/**"
    

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test Build
        working-directory: documentation
        run: |
          corepack enable
          yarn install --immutable
          yarn build
